# Generated by Django 4.0 on 2021-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('urlToImage', models.URLField()),
                ('publishedAt', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
