# Generated by Django 4.0 on 2021-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
