# Generated by Django 4.0 on 2021-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_news_author_alter_news_source_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
